import { describe, expect, it } from "vitest";
import {
  apiDetail,
  barFraction,
  describeStep,
  formatMetric,
  isSettled,
  orderSteps,
  parseCodeBlocks,
  starterSteps,
} from "../utils/workflows";

// A script shaped exactly as codegen.generate_script writes one, headings included.
const SCRIPT = `"""Titanic — generated by Crescent Forge."""

import pandas as pd

# step 1 of 3 — load_csv: read the CSV into a table
DATA_PATH = 'titanic.csv'
df = pd.read_csv(DATA_PATH)

# step 2 of 3 — select_target: the column the model predicts
TARGET = 'survived'

# step 3 of 3 — train_model: fit the chosen algorithm
model = LogisticRegression(max_iter=1000)
`;

describe("parseCodeBlocks", () => {
  it("splits the script on the headings codegen.py writes, keeping the step kind", () => {
    const blocks = parseCodeBlocks(SCRIPT);
    expect(blocks.map((b) => b.kind)).toEqual(["", "load_csv", "select_target", "train_model"]);
    expect(blocks.map((b) => b.position)).toEqual([null, 1, 2, 3]);
  });

  it("keeps every line of the block under its own heading", () => {
    const blocks = parseCodeBlocks(SCRIPT);
    expect(blocks[1]!.lines).toEqual(["DATA_PATH = 'titanic.csv'", "df = pd.read_csv(DATA_PATH)"]);
    expect(blocks[3]!.lines).toEqual(["model = LogisticRegression(max_iter=1000)"]);
  });

  it("reads the heading text so the block can be labelled the way the server labelled it", () => {
    expect(parseCodeBlocks(SCRIPT)[2]!.heading).toBe("the column the model predicts");
  });

  it("returns the header alone when there are no step headings", () => {
    expect(parseCodeBlocks("import pandas as pd").map((b) => b.kind)).toEqual([""]);
  });
});

describe("orderSteps", () => {
  it("sorts into the order the pipeline runs, not the order they were added", () => {
    const added = [{ kind: "evaluate" }, { kind: "train_model" }, { kind: "load_csv" }, { kind: "select_target" }];
    expect(orderSteps(added).map((s) => s.kind)).toEqual(["load_csv", "select_target", "train_model", "evaluate"]);
  });

  it("puts scaling after the split, which is what stops the scaler seeing the test rows", () => {
    const added = [{ kind: "scale_features" }, { kind: "train_test_split" }];
    expect(orderSteps(added).map((s) => s.kind)).toEqual(["train_test_split", "scale_features"]);
  });
});

describe("starterSteps", () => {
  it("opens a classification workflow on a sequence the server will accept", () => {
    expect(starterSteps("tabular_classification").map((s) => s.kind)).toEqual([
      "load_csv", "select_target", "handle_missing", "train_test_split", "train_model", "evaluate",
    ]);
  });

  it("gives a forecast its lag step and turns shuffling off", () => {
    const steps = starterSteps("timeseries_forecast", "revenue");
    expect(steps.map((s) => s.kind)).toContain("lag_features");
    expect(steps.find((s) => s.kind === "lag_features")!.params.column).toBe("revenue");
    expect(steps.find((s) => s.kind === "train_test_split")!.params.shuffle).toBe(false);
  });

  it("fills the target in, because the server refuses a workflow whose target is blank", () => {
    const steps = starterSteps("tabular_classification", "species");
    expect(steps.find((s) => s.kind === "select_target")!.params.column).toBe("species");
  });

  it("makes an LLM playground exactly one prompt step, with the question already in it", () => {
    const steps = starterSteps("llm_playground", "Summarise this.");
    expect(steps.map((s) => s.kind)).toEqual(["prompt"]);
    expect(steps[0]!.params.prompt).toBe("Summarise this.");
  });
});

describe("describeStep", () => {
  it("says what the split will actually do, in rows a person can picture", () => {
    expect(describeStep("train_test_split", { test_size: 0.25, random_state: 7, shuffle: false }))
      .toBe("Holds back 25% of the rows, in order, seed 7.");
  });

  it("names the columns a cleaning step touches, and says so when it touches all of them", () => {
    expect(describeStep("handle_missing", { strategy: "median", columns: ["age"] })).toBe("Fills gaps in age using Median.");
    expect(describeStep("handle_missing", { strategy: "drop_rows", columns: [] })).toBe("Drops rows with gaps in every applicable column.");
  });

  it("admits when a required choice has not been made", () => {
    expect(describeStep("select_target", { column: "" })).toBe("No target chosen yet.");
  });
});

describe("run helpers", () => {
  it("treats only a finished run as settled, which is what stops the polling", () => {
    expect(isSettled({ status: "queued" } as never)).toBe(false);
    expect(isSettled({ status: "running" } as never)).toBe(false);
    expect(isSettled({ status: "succeeded" } as never)).toBe(true);
    expect(isSettled({ status: "failed" } as never)).toBe(true);
  });

  it("draws a bar only for the scores that are bounded", () => {
    expect(barFraction("accuracy", 0.87)).toBeCloseTo(0.87);
    expect(barFraction("mae", 12.4)).toBeNull();
  });

  it("formats a percentage as one and leaves a token count whole", () => {
    expect(formatMetric("mape_percent", 4.125)).toBe("4.13%");
    expect(formatMetric("tokens", 412)).toBe("412");
  });
});

describe("apiDetail", () => {
  it("shows the learner-readable sentence steps.py wrote on a 400", () => {
    const err = { statusCode: 400, data: { detail: "The first step must be 'load_csv'." } };
    expect(apiDetail(err, "fallback")).toBe("The first step must be 'load_csv'.");
  });

  it("keeps a server exception message off the screen", () => {
    const err = { statusCode: 500, data: { detail: "KeyError: 'params'" } };
    expect(apiDetail(err, "fallback")).toBe("fallback");
  });
});
